version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db", "python", "manage.py", "runserver", "0:8000"]